# -*- coding: utf-8 -*-
"""YOLOv8_Vehicle_Detection (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUNWXjY_1CO_sDmT7ZwtdIAIT5lwwCNA

#  YOLOv8 Vehicle Detection – Full Project Notebook
Complete training, validation, metrics & prediction.
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics
from ultralytics import YOLO
import os, cv2
import matplotlib.pyplot as plt

"""## Dataset Path Setup"""

dataset_path = '/content/drive/MyDrive/yolo v8 detection/yolo v8 vehicle'
print('Dataset Exists:', os.path.exists(dataset_path))
print('Files:', os.listdir(dataset_path))

"""## Load Model"""

model = YOLO('yolov8s.pt')

"""# Train YOLOv8"""

model.train(
    data=f"{dataset_path}/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    workers=4,
    device=0,
    plots=True
)

"""## Validate Model"""

metrics = model.val(data=f'{dataset_path}/data.yaml')
metrics

"""## Prediction + Annotated Outputs"""

test_path = f"{dataset_path}/test/images"
pred_results = model.predict(source=test_path, save=True, conf=0.25)
output_dir = pred_results[0].save_dir
print('Annotated Output Folder:', output_dir)

for img_name in os.listdir(output_dir):
    if img_name.lower().endswith(('.jpg','.png','.jpeg')):
        img_path = os.path.join(output_dir, img_name)
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.figure(figsize=(10,10))
        plt.imshow(img)
        plt.title(f'Annotated Image: {img_name}', fontsize=15)
        plt.axis('off')
        plt.show()

"""## Metrics Visualization"""



import os
import matplotlib.pyplot as plt
import cv2

for root, dirs, files in os.walk("runs"):
    for file in files:
        if file.endswith(".png"):
            print("Found:", os.path.join(root, file))
            img = cv2.imread(os.path.join(root, file))
            if img is not None:
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                plt.figure(figsize=(8,8))
                plt.imshow(img)
                plt.title(file)
                plt.axis("off")
                plt.show()
